let briefcaseImages = [
	{
		id: "1",
		category: "identidad",
		namePrimary: "Creamos Marca",
		urlPrimary: "zooquillapampa.jpg",
		imagesSecondary: [
			{name: "zooquillapampa.jpg", url: "zooquillapampa.jpg"},
			{name: "cross", url: "cross.jpg"},
			{name: "abogados", url: "abogados.jpg"},
			{name: "powergym", url: "powergym.jpg"},
			{name: "apricot", url: "apricot.jpg"},
		],
	},
	{
		id: "2",
		category: "branding",
		namePrimary: "Identidad Corporativa",
		urlPrimary: "sebastarjeta.jpg",
		imagesSecondary: [
			{name: "sebastarjeta.jpg", url: "sebastarjeta.jpg"},
			{name: "cross", url: "cross2.jpg"},
			{name: "fitness nutrition", url: "fitnessnutrition.jpg"},
			{name: "procope", url: "procope.jpg"},
			{name: "fitness nutrition", url: "fitnessnutrition2.jpg"},
		],
	},
	{
		id: "3",
		category: "impresos",
		namePrimary: "Flyer / Brochure",
		urlPrimary: "volanteesika.jpg",
		imagesSecondary: [
			{name: "volanteesika.jpg", url: "volanteesika.jpg"},
			{name: "triptico premios juntos", url: "tripticopremiosjuntos.jpg"},
			{name: "volante power gym", url: "volantepowergym.jpg"},
			{name: "room 21b", url: "room21b.jpg"},
			{name: "volante unica", url: "volanteunica.jpg"},
		],
	},
	{
		id: "4",
		category: "miseláneo",
		namePrimary: "Branding",
		urlPrimary: "jehovadioshombre.jpg",
		imagesSecondary: [
			{name: "jehovadioshombre.jpg", url: "jehovadioshombre.jpg"},
			{name: "taza", url: "taza.jpg"},
			{name: "tar", url: "tar.jpg"},
			{name: "cristo mujer", url: "cristomujer.jpg"},
			{name: "triptico esika", url: "tripticoesika.jpg"},
		],
	},
	{
		id: "5",
		category: "image-a",
		namePrimary: "image-a",
		urlPrimary: "a-1.jpg",
		urlSecond: "a-2.jpg",
		imagesSecondary: [
			{name: "a-1", url: "a-1.jpg"},
			{name: "a-2", url: "a-2.jpg"},
		],
	},
	{
		id: "6",
		category: "web",
		namePrimary: "Social Media",
		urlPrimary: "web.jpg",
		imagesSecondary: [
			{name: "web.jpg", url: "web.jpg"},
			{name: "web banco financiero", url: "webbancofinanciero.jpg"},
			{name: "face mock", url: "facemock.jpg"},
			{name: "post valora", url: "postvalora.jpg"},
		],
	},
	{
		id: "7",
		category: "prensa",
		namePrimary: "Magazine",
		urlPrimary: "lebellederm.jpg",
		imagesSecondary: [
			{name: "lebel lederm", url: "lebellederm.jpg"},
			{name: "brucke cy-zone", url: "bruckecy-zone.jpg"},
			{name: "esika reyna", url: "esikareyna.jpg"},
			{name: "lebel revista", url: "lebelchicarevista.jpg"},
			{name: "belcorp", url: "belcorp.jpg"},
		],
	},
	{
		id: "8",
		category: "indoor",
		namePrimary: "Poster / Display",
		urlPrimary: "chicabanner.jpg",
		imagesSecondary: [
			{name: "chica banner", url: "chicabanner.jpg"},
			{name: "afiche coqueto", url: "afichecoqueta.jpg"},
			{name: "banner esika", url: "banneresika.jpg"},
			{name: "banner scotiabank", url: "bannerscotiabank.jpg"},
			{name: "colgante banco", url: "colgantebanco.jpg"},
		],
	},
	{
		id: "9",
		category: "outdoor",
		namePrimary: "Banner / Billboard / Flags",
		urlPrimary: "outdoorbanner.jpg",
		imagesSecondary: [
			{name: "outdoor banner", url: "outdoorbanner.jpg"},
			{name: "valla lebel", url: "vallalebel.jpg"},
			{name: "paradero dental", url: "paraderodental.jpg"},
			{name: "valla movil chico flip", url: "vallamovilchicoflip.jpg"},
			{name: "valla esika coqueto", url: "Vallaesikacoqueto.jpg"},
		],
	},
	{
		id: "10",
		category: "branding",
		namePrimary: "Identidad Corporativa",
		urlPrimary: "creativestudio.jpg",
		imagesSecondary: [
			{name: "creative estudio", url: "creativestudio.jpg"},
			{name: "mac", url: "mac.jpg"},
			{name: "directo", url: "directo.jpg"},
			{name: "acuarius", url: "acuarius.jpg"},
			{name: "labok", url: "labok.jpg"},
		],
	},
	{
		id: "11",
		category: "impresos",
		namePrimary: "Flyer / Brochure",
		urlPrimary: "pizzaraul.jpg",
		imagesSecondary: [
			{name: "pizza raul", url: "pizzaraul.jpg"},
			{name: "unica", url: "unica.jpg"},
			{name: "volante lebel", url: "volantelebel.jpg"},
			{name: "pizza raul", url: "pizzaraul2.jpg"},
			{name: "juguetes", url: "juguetes.jpg"},
		],
	},
	{
		id: "12",
		category: "identidad",
		namePrimary: "Creamos Marca",
		urlPrimary: "strong.jpg",
		imagesSecondary: [
			{name: "strong", url: "strong.jpg"},
			{name: "barber shop sebas", url: "barbershopsebas.jpg"},
			{name: "body care", url: "bodycare.jpg"},
			{name: "cat dog", url: "catdog.jpg"},
			{name: "directo", url: "directo2.jpg"},
		],
	},
	{
		id: "13",
		category: "image-b",
		namePrimary: "image-b",
		urlPrimary: "b-1.jpg",
		urlSecond: "b-2.jpg",
		imagesSecondary: [
			{name: "b-1", url: "b-1.jpg"},
			{name: "b-2", url: "b-2.jpg"},
		],
	},
	{
		id: "14",
		category: "outdoor",
		namePrimary: "Banner / Billboard / Flags",
		urlPrimary: "vallanavidad.jpg",
		imagesSecondary: [
			{name: "valla navidad", url: "vallanavidad.jpg"},
			{name: "panel lebel", url: "panellebel.jpg"},
			{name: "movil fary", url: "movilfary.jpg"},
			{name: "billboard bus", url: "billboardbus.jpg"},
			{name: "paradero", url: "paradero2.jpg"},
		],
	},
	{
		id: "15",
		category: "impresos",
		namePrimary: "Flyer / Brochure",
		urlPrimary: "room21a.jpg",
		imagesSecondary: [
			{name: "room 21 a", url: "room21a.jpg"},
			{name: "juntos", url: "juntos.jpg"},
			{name: "gmo", url: "gmo.jpg"},
			{name: "volante pizza raul", url: "volantepizzaraul.jpg"},
			{name: "volante unica", url: "volanteunica2.jpg"},
		],
	},
	{
		id: "16",
		category: "miseláneo",
		namePrimary: "Branding",
		urlPrimary: "cristohombre2.jpg",
		imagesSecondary: [
			{name: "cristo hombre", url: "cristohombre2.jpg"},
			{name: "calendario eva", url: "calendarioeva.jpg"},
			{name: "bolsa esika", url: "bolsaesika.jpg"},
			{name: "rey mujer", url: "reymujer.jpg"},
			{name: "esika reyna", url: "esikareyna2.jpg"},
		],
	},
	{
		id: "17",
		category: "web",
		namePrimary: "Social Media",
		urlPrimary: "postvalora.jpg",
		imagesSecondary: [
			{name: "post valora", url: "postvalora2.jpg"},
			{name: "productos mac", url: "productosmac.jpg"},
			{name: "web nutricion", url: "webnutriciongym.jpg"},
			{name: "web banco financiero", url: "webbancofinanciero2.jpg"},
		],
	},
	{
		id: "18",
		category: "prensa",
		namePrimary: "Magazine",
		urlPrimary: "prensamarko.jpg",
		imagesSecondary: [
			{name: "prensa marko", url: "prensamarko.jpg"},
			{name: "libro macroeconomica andina", url: "libromacroeconomicaandina.jpg"},
			{name: "revista rose rose", url: "revistaroserose.jpg"},
			{name: "revista portada cosas", url: "revistaportadacosas.jpg"},
			{name: "revista lebel", url: "revistalebel.jpg"},
		],
	},
	{
		id: "19",
		category: "outdoor",
		namePrimary: "Poster / Display",
		urlPrimary: "busstop.jpg",
		imagesSecondary: [
			{name: "bus stop", url: "busstop.jpg"},
			{name: "valla doble cy-zone", url: "valladoblecyzone.jpg"},
			{name: "bus stop muay thai", url: "busstopmuaythai.jpg"},
			{name: "bus stop esika", url: "busstopesika.jpg"},
		],
	},
	{
		id: "20",
		category: "indoor",
		namePrimary: "Poster / Display",
		urlPrimary: "misescotiabank.jpg",
		imagesSecondary: [
			{name: "mise scotiabank", url: "misescotiabank.jpg"},
			{name: "panel unica, cyzone", url: "panelunicacyzone.jpg"},
			{name: "afiche cy-zone quierete", url: "afichecy-zonequierete.jpg"},
			{name: " banderola look cy-zone", url: "banderolalookcy-zone.jpg"},
			{name: "banner esika bravio", url: "banneresikabravio.jpg"},
		],
	},
	{
		id: "21",
		category: "image-c",
		namePrimary: "image-c",
		urlPrimary: "c-1.jpg",
		urlSecond: "c-2.jpg",
		imagesSecondary: [
			{name: "c-1", url: "c-1.jpg"},
			{name: "c-2", url: "c-2.jpg"},
		],
	},
];
