let briefcaseImagesDesktop = [
  {
    id: "1",
    category: "identidad",
    namePrimary: "Creamos Marca",
    urlPrimary: "zooquillapampa.webp",
    imagesSecondary: [
      { name: "zooquillapampa.webp", url: "zooquillapampa.webp" },
      { name: "cross", url: "cross.webp" },
      { name: "abogados", url: "abogados.webp" },
      { name: "powergym", url: "powergym.webp" },
      { name: "apricot", url: "apricot.webp" },
    ],
  },
  {
    id: "2",
    category: "branding",
    namePrimary: "Identidad Corporativa",
    urlPrimary: "sebastarjeta.webp",
    imagesSecondary: [
      { name: "sebastarjeta.webp", url: "sebastarjeta.webp" },
      { name: "cross", url: "cross2.webp" },
      { name: "fitness nutrition", url: "fitnessnutrition.webp" },
      { name: "procope", url: "procope.webp" },
      { name: "fitness nutrition", url: "fitnessnutrition2.webp" },
    ],
  },
  {
    id: "3",
    category: "impresos",
    namePrimary: "Flyer / Brochure",
    urlPrimary: "volanteesika.webp",
    imagesSecondary: [
      { name: "volanteesika.webp", url: "volanteesika.webp" },
      { name: "triptico premios juntos", url: "tripticopremiosjuntos.webp" },
      { name: "volante power gym", url: "volantepowergym.webp" },
      { name: "room 21b", url: "room21b.webp" },
      { name: "volante unica", url: "volanteunica.webp" },
    ],
  },
  {
    id: "4",
    category: "miseláneo",
    namePrimary: "Branding",
    urlPrimary: "jehovadioshombre.webp",
    imagesSecondary: [
      { name: "jehovadioshombre.webp", url: "jehovadioshombre.webp" },
      { name: "taza", url: "taza.webp" },
      { name: "tar", url: "tar.webp" },
      { name: "cristo mujer", url: "cristomujer.webp" },
      { name: "triptico esika", url: "tripticoesika.webp" },
    ],
  },
  {
    id: "5",
    category: "image-a",
    namePrimary: "image-a",
    urlPrimary: "a-1.webp",
    urlSecond: "a-2.webp",
    imagesSecondary: [
      { name: "a-1", url: "a-1.webp" },
      { name: "a-2", url: "a-2.webp" },
    ],
  },
  {
    id: "6",
    category: "web",
    namePrimary: "Social Media",
    urlPrimary: "web.webp",
    imagesSecondary: [
      { name: "web.webp", url: "web.webp" },
      { name: "web banco financiero", url: "webbancofinanciero.webp" },
      { name: "face mock", url: "facemock.webp" },
      { name: "post valora", url: "postvalora.webp" },
    ],
  },
  {
    id: "7",
    category: "prensa",
    namePrimary: "Magazine",
    urlPrimary: "lebellederm.webp",
    imagesSecondary: [
      { name: "lebel lederm", url: "lebellederm.webp" },
      { name: "brucke cy-zone", url: "bruckecy-zone.webp" },
      { name: "esika reyna", url: "esikareyna.webp" },
      { name: "lebel revista", url: "lebelchicarevista.webp" },
      { name: "belcorp", url: "belcorp.webp" },
    ],
  },
  {
    id: "8",
    category: "indoor",
    namePrimary: "Poster / Display",
    urlPrimary: "chicabanner.webp",
    imagesSecondary: [
      { name: "chica banner", url: "chicabanner.webp" },
      { name: "afiche coqueto", url: "afichecoqueta.webp" },
      { name: "banner esika", url: "banneresika.webp" },
      { name: "banner scotiabank", url: "bannerscotiabank.webp" },
      { name: "colgante banco", url: "colgantebanco.webp" },
    ],
  },
  {
    id: "9",
    category: "outdoor",
    namePrimary: "Banner / Billboard / Flags",
    urlPrimary: "outdoorbanner.webp",
    imagesSecondary: [
      { name: "outdoor banner", url: "outdoorbanner.webp" },
      { name: "valla lebel", url: "vallalebel.webp" },
      { name: "paradero dental", url: "paraderodental.webp" },
      { name: "valla movil chico flip", url: "vallamovilchicoflip.webp" },
      { name: "valla esika coqueto", url: "vallaesikacoqueto.webp" },
    ],
  },
  {
    id: "10",
    category: "branding",
    namePrimary: "Identidad Corporativa",
    urlPrimary: "creativestudio.webp",
    imagesSecondary: [
      { name: "creative estudio", url: "creativestudio.webp" },
      { name: "mac", url: "mac.webp" },
      { name: "directo", url: "directo.webp" },
      { name: "acuarius", url: "acuarius.webp" },
      { name: "labok", url: "labok.webp" },
    ],
  },
  {
    id: "11",
    category: "impresos",
    namePrimary: "Flyer / Brochure",
    urlPrimary: "pizzaraul.webp",
    imagesSecondary: [
      { name: "pizza raul", url: "pizzaraul.webp" },
      { name: "unica", url: "unica.webp" },
      { name: "volante lebel", url: "volantelebel.webp" },
      { name: "pizza raul", url: "pizzaraul2.webp" },
      { name: "juguetes", url: "juguetes.webp" },
    ],
  },
  {
    id: "12",
    category: "identidad",
    namePrimary: "Creamos Marca",
    urlPrimary: "strong.webp",
    imagesSecondary: [
      { name: "strong", url: "strong.webp" },
      { name: "barber shop sebas", url: "barbershopsebas.webp" },
      { name: "body care", url: "bodycare.webp" },
      { name: "cat dog", url: "catdog.webp" },
      { name: "directo", url: "directo2.webp" },
    ],
  },
  {
    id: "13",
    category: "image-b",
    namePrimary: "image-b",
    urlPrimary: "b-1.webp",
    urlSecond: "b-2.webp",
    imagesSecondary: [
      { name: "b-1", url: "b-1.webp" },
      { name: "b-2", url: "b-2.webp" },
    ],
  },
  {
    id: "14",
    category: "outdoor",
    namePrimary: "Banner / Billboard / Flags",
    urlPrimary: "vallanavidad.webp",
    imagesSecondary: [
      { name: "valla navidad", url: "vallanavidad.webp" },
      { name: "panel lebel", url: "panellebel.webp" },
      { name: "movil fary", url: "movilfary.webp" },
      { name: "billboard bus", url: "billboardbus.webp" },
      { name: "paradero", url: "paradero2.webp" },
    ],
  },
  {
    id: "15",
    category: "impresos",
    namePrimary: "Flyer / Brochure",
    urlPrimary: "room21a.webp",
    imagesSecondary: [
      { name: "room 21 a", url: "room21a.webp" },
      { name: "juntos", url: "juntos.webp" },
      { name: "gmo", url: "gmo.webp" },
      { name: "volante pizza raul", url: "volantepizzaraul.webp" },
      { name: "volante unica", url: "volanteunica2.webp" },
    ],
  },
  {
    id: "16",
    category: "miseláneo",
    namePrimary: "Branding",
    urlPrimary: "cristohombre2.webp",
    imagesSecondary: [
      { name: "cristo hombre", url: "cristohombre2.webp" },
      { name: "calendario eva", url: "calendarioeva.webp" },
      { name: "bolsa esika", url: "bolsaesika.webp" },
      { name: "rey mujer", url: "reymujer.webp" },
      { name: "esika reyna", url: "esikareyna2.webp" },
    ],
  },
  {
    id: "17",
    category: "web",
    namePrimary: "Social Media",
    urlPrimary: "postvalora.webp",
    imagesSecondary: [
      { name: "post valora", url: "postvalora2.webp" },
      { name: "productos mac", url: "productosmac.webp" },
      { name: "web nutricion", url: "webnutriciongym.webp" },
      { name: "web banco financiero", url: "webbancofinanciero2.webp" },
    ],
  },
  {
    id: "18",
    category: "prensa",
    namePrimary: "Magazine",
    urlPrimary: "prensamarko.webp",
    imagesSecondary: [
      { name: "prensa marko", url: "prensamarko.webp" },
      {
        name: "libro macroeconomica andina",
        url: "libromacroeconomicaandina.webp",
      },
      { name: "revista rose rose", url: "revistaroserose.webp" },
      { name: "revista portada cosas", url: "revistaportadacosas.webp" },
      { name: "revista lebel", url: "revistalebel.webp" },
    ],
  },
  {
    id: "19",
    category: "outdoor",
    namePrimary: "Poster / Display",
    urlPrimary: "busstop.webp",
    imagesSecondary: [
      { name: "bus stop", url: "busstop.webp" },
      { name: "valla doble cy-zone", url: "valladoblecyzone.webp" },
      { name: "bus stop muay thai", url: "busstopmuaythai.webp" },
      { name: "bus stop esika", url: "busstopesika.webp" },
      { name: "paneles", url: "paneles.webp" },
    ],
  },
  {
    id: "20",
    category: "indoor",
    namePrimary: "Poster / Display",
    urlPrimary: "misescotiabank.webp",
    imagesSecondary: [
      { name: "mise scotiabank", url: "misescotiabank.webp" },
      { name: "panel unica, cyzone", url: "panelunicacyzone.webp" },
      { name: "afiche cy-zone quierete", url: "afichecy-zonequierete.webp" },
      { name: " banderola look cy-zone", url: "banderolalookcy-zone.webp" },
      { name: "banner esika bravio", url: "banneresikabravio.webp" },
    ],
  },
  {
    id: "21",
    category: "image-c",
    namePrimary: "image-c",
    urlPrimary: "c-1.webp",
    urlSecond: "c-2.webp",
    imagesSecondary: [
      { name: "c-1", url: "c-1.webp" },
      { name: "c-2", url: "c-2.webp" },
    ],
  },
];

let briefcaseImagesMobile = [
  {
    id: "1",
    category: "identidad",
    namePrimary: "Creamos Marca",
    urlPrimary: "strong.webp",
    imagesSecondary: [
      { name: "strong", url: "strong.webp" },
      { name: "barber shop sebas", url: "barbershopsebas.webp" },
      { name: "body care", url: "bodycare.webp" },
      { name: "cat dog", url: "catdog.webp" },
      { name: "directo", url: "directo2.webp" },
    ],
  },
  {
    id: "2",
    category: "branding",
    namePrimary: "Identidad Corporativa",
    urlPrimary: "creativestudio.webp",
    imagesSecondary: [
      { name: "creative estudio", url: "creativestudio.webp" },
      { name: "mac", url: "mac.webp" },
      { name: "directo", url: "directo.webp" },
      { name: "acuarius", url: "acuarius.webp" },
      { name: "labok", url: "labok.webp" },
    ],
  },
  {
    id: "3",
    category: "branding",
    namePrimary: "Identidad Corporativa",
    urlPrimary: "creativestudio.webp",
    imagesSecondary: [
      { name: "creative estudio", url: "creativestudio.webp" },
      { name: "mac", url: "mac.webp" },
      { name: "directo", url: "directo.webp" },
      { name: "acuarius", url: "acuarius.webp" },
      { name: "labok", url: "labok.webp" },
    ],
  },
  {
    id: "4",
    category: "impresos",
    namePrimary: "Flyer / Brochure",
    urlPrimary: "volanteesika.webp",
    imagesSecondary: [
      { name: "volanteesika.webp", url: "volanteesika.webp" },
      { name: "triptico premios juntos", url: "tripticopremiosjuntos.webp" },
      { name: "volante power gym", url: "volantepowergym.webp" },
      { name: "room 21b", url: "room21b.webp" },
      { name: "volante unica", url: "volanteunica.webp" },
    ],
  },

  {
    id: "5",
    category: "prensa",
    namePrimary: "Magazine",
    urlPrimary: "lebellederm.webp",
    imagesSecondary: [
      { name: "lebel lederm", url: "lebellederm.webp" },
      { name: "brucke cy-zone", url: "bruckecy-zone.webp" },
      { name: "esika reyna", url: "esikareyna.webp" },
      { name: "lebel revista", url: "lebelchicarevista.webp" },
      { name: "belcorp", url: "belcorp.webp" },
    ],
  },
  {
    id: "6",
    category: "image-a",
    namePrimary: "image-a",
    urlPrimary: "a-1.webp",
    urlSecond: "a-2.webp",
    imagesSecondary: [
      { name: "a-1", url: "a-1.webp" },
      { name: "a-2", url: "a-2.webp" },
    ],
  },
  {
    id: "7",
    category: "indoor",
    namePrimary: "Poster / Display",
    urlPrimary: "chicabanner.webp",
    imagesSecondary: [
      { name: "chica banner", url: "chicabanner.webp" },
      { name: "afiche coqueto", url: "afichecoqueta.webp" },
      { name: "banner esika", url: "banneresika.webp" },
      { name: "banner scotiabank", url: "bannerscotiabank.webp" },
      { name: "colgante banco", url: "colgantebanco.webp" },
    ],
  },
  {
    id: "8",
    category: "outdoor",
    namePrimary: "Banner / Billboard / Flags",
    urlPrimary: "outdoorbanner.webp",
    imagesSecondary: [
      { name: "outdoor banner", url: "outdoorbanner.webp" },
      { name: "valla lebel", url: "vallalebel.webp" },
      { name: "paradero dental", url: "paraderodental.webp" },
      { name: "valla movil chico flip", url: "vallamovilchicoflip.webp" },
      { name: "valla esika coqueto", url: "vallaesikacoqueto.webp" },
    ],
  },
  {
    id: "9",
    category: "web",
    namePrimary: "Social Media",
    urlPrimary: "postvalora.webp",
    imagesSecondary: [
      { name: "post valora", url: "postvalora2.webp" },
      { name: "productos mac", url: "productosmac.webp" },
      { name: "web nutricion", url: "webnutriciongym.webp" },
      { name: "web banco financiero", url: "webbancofinanciero2.webp" },
    ],
  },
  {
    id: "10",
    category: "miseláneo",
    namePrimary: "Branding",
    urlPrimary: "jehovadioshombre.webp",
    imagesSecondary: [
      { name: "jehovadioshombre.webp", url: "jehovadioshombre.webp" },
      { name: "taza", url: "taza.webp" },
      { name: "tar", url: "tar.webp" },
      { name: "cristo mujer", url: "cristomujer.webp" },
      { name: "triptico esika", url: "tripticoesika.webp" },
    ],
  },
  {
    id: "11",
    category: "image-b",
    namePrimary: "image-b",
    urlPrimary: "b-1.webp",
    urlSecond: "b-2.webp",
    imagesSecondary: [
      { name: "b-1", url: "b-1.webp" },
      { name: "b-2", url: "b-2.webp" },
    ],
  },
];
